### ISSUE TITLE
Fire Achievement for Cathedrals failed

### ISSUE THREAD

**Issue by stanolacko** [TheCodeLabsDevs/CarrotCastle#6]
Achievements for Inns & Cathedrals not fired (even in official build 1.1.0 (3)).
It seams that 
`if(scoredBuilding.hasFeature(Cathedral.class))` is not working as requested in `ScoreEventListener`
Due to this, Darmstadt achievements is only proposal, because they were not tested, due to this issue.

Tested on master (1.1.0) with OpenJDK 14.0.2

**Comment by deadlocker8** [comment]
Those achievements will only be evaluated and unlocked if in multiplayer. To be more precise at least two different clients needs to participate in a lobby. If you start a game with only one client those achievements will not be available. We made this decision to increase the difficulty a little bit as it would be too easy to unlock those achievements if you start a game with only one client and play only for yourself.

Did you started the game with a single client or can you confirm that the achievements are also not unlocked if 2 or more clients are in the lobby?

**Comment by stanolacko** [comment]
Ok. It seams to be to fair. But for example other acievements is working fine, like "Forewer allone" (of course it's working ;-)
But "Addicted", "A Whole legion" is increasing. 
When played two clients that I got Notre Damm.
So no bug but maybe it will be goot to mention it in Achievements list - that fisabled for standalone game, or something like that? ;-)

**Comment by deadlocker8** [comment]
Create an issue for adding an explanation to the achievements overview:
https://thecodelabs.de/TheCodeLabs/CarrotCastle/-/issues/202
